import type { InvoiceJob } from "@/lib/invoice-types";
import { buildJobSummary } from "@/lib/invoice-parser";

export function buildDemoJob(jobId: string): InvoiceJob {
  const records: InvoiceJob["records"] = [
    {
      id: "demo-001",
      fileName: "数电票-餐饮.pdf",
      invoiceType: "数电票 PDF",
      invoiceNumber: "241001230045",
      invoiceDate: "2026-05-02",
      sellerName: "杭州云栖餐饮管理有限公司",
      buyerName: "宁波春禾贸易有限公司",
      amountExcludingTax: 188.68,
      taxAmount: 11.32,
      amountIncludingTax: 200,
      remarkOrItem: "*餐饮服务*工作午餐",
      checkCodeLast6: "593201",
      taxpayerId: "91330201MA2AAAAA1X",
      statusLabel: "识别成功",
      duplicate: false,
      duplicateReason: "",
      notes: [],
    },
    {
      id: "demo-002",
      fileName: "普票-办公用品.pdf",
      invoiceType: "普通电子发票 PDF",
      invoiceNumber: "240009876543",
      invoiceDate: "2026-05-08",
      sellerName: "上海木川办公设备有限公司",
      buyerName: "宁波春禾贸易有限公司",
      amountExcludingTax: 450,
      taxAmount: 22.5,
      amountIncludingTax: 472.5,
      remarkOrItem: "*办公用品*标签纸与文件夹",
      checkCodeLast6: "401188",
      taxpayerId: "91330201MA2AAAAA1X",
      statusLabel: "识别成功",
      duplicate: true,
      duplicateReason: "发票号码或核心金额组合重复",
      notes: [],
    },
    {
      id: "demo-003",
      fileName: "普票-办公用品-重复.pdf",
      invoiceType: "普通电子发票 PDF",
      invoiceNumber: "240009876543",
      invoiceDate: "2026-05-08",
      sellerName: "上海木川办公设备有限公司",
      buyerName: "宁波春禾贸易有限公司",
      amountExcludingTax: 450,
      taxAmount: 22.5,
      amountIncludingTax: 472.5,
      remarkOrItem: "*办公用品*标签纸与文件夹",
      checkCodeLast6: "401188",
      taxpayerId: "91330201MA2AAAAA1X",
      statusLabel: "识别成功",
      duplicate: true,
      duplicateReason: "发票号码或核心金额组合重复",
      notes: [],
    },
    {
      id: "demo-004",
      fileName: "数电票-差旅.pdf",
      invoiceType: "数电票 PDF",
      invoiceNumber: "241001230098",
      invoiceDate: "2026-05-11",
      sellerName: "杭州东站商务服务有限公司",
      buyerName: "宁波春禾贸易有限公司",
      amountExcludingTax: null,
      taxAmount: 0,
      amountIncludingTax: 160,
      remarkOrItem: "*客运服务*高铁车票",
      checkCodeLast6: "",
      taxpayerId: "91330201MA2AAAAA1X",
      statusLabel: "信息不完整",
      duplicate: false,
      duplicateReason: "",
      notes: ["缺少金额合计", "校验码未完整提取"],
    },
  ];
  const failures: InvoiceJob["failures"] = [
    {
      fileName: "扫描件-示例.pdf",
      reason: "未检测到足够的文本层，当前 demo 仅支持可复制文本的电子发票 PDF。",
    },
  ];

  return {
    jobId,
    createdAt: new Date().toISOString(),
    mode: "demo",
    sourceLabel: "示例数据体验",
    records,
    failures,
    summary: buildJobSummary(records, failures),
  };
}